# This is a basic workflow to help you get started with Actions

name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            #     - name: Install
            #       uses: CultureHQ/actions-yarn@master
            #       with:
            #         args: install

            #     - name: Build
            #       uses: CultureHQ/actions-yarn@master
            #       with:
            #         args: build

            - name: Publish to Zeit
              uses: amondnet/vercel-action@v19.0.1+1
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  github-comment: true,
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  github-deployment: false
                  vercel-project-id: ${{ secrets.PROJECT_ID }}
                  vercel-org-id: ${{ secrets.ORG_ID }}
                  vercel-args: '--prod'
