# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
      
#     - name: Install
#       uses: CultureHQ/actions-yarn@master
#       with:
#         args: install
    
#     - name: Build
#       uses: CultureHQ/actions-yarn@master
#       with:
#         args: build
    
    - name: Publish to Zeit
      uses: amondnet/vercel-action@v19.0.1+1
      with:
        # Vercel token
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        # if you want to comment on pr and commit, set true, default: true
        github-comment: true,
        # if you want to comment on pr and commit, set token
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # if you want to create github deployment, set true, default: false
        github-deployment: false
        # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-args: '--prod'
